name: DevOps-GitHibActions
on: push
jobs:
  # Build Job now
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Checkout Code
        uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Install Node
        uses: actions/setup-node@v4
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Install Dependencies
        run: npm install
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Build Project
        run: npm run build
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist
 # Deploy Job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.REPO_KEY }}
          publish_dir: ./dist
         
